name: Deploy Portfolio

on:
  push:
    branches:
      - development

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: build image
        run: |
          echo "build image with latest code...."
          sudo docker compose build

      - name: run container
        run: |
          echo "running container with new image"

          echo "show current directory"
          pwd
          sudo docker compose up -d