name: Test Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: adil

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show System Information
        run: |
          echo "Runner is working!"
          whoami
          pwd
          hostname
          docker --version
          docker compose version